[package]
name = "daylight-metal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck.workspace = true
daylight-core = { path = "../daylight-core" }
serde.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-metal.workspace = true
